# Generated by Django 3.0.3 on 2020-11-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIncidentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('incident_department', models.TextField(max_length=300)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('incident_location', models.TextField(max_length=100)),
                ('initial_severity', models.CharField(max_length=30)),
                ('suspected_cause', models.TextField(max_length=100)),
                ('immediate_action_taken', models.TextField(max_length=100)),
                ('sub_incident_type', models.CharField(max_length=30)),
            ],
        ),
    ]
